# Generated by Django 3.2.18 on 2023-04-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_actors',
            new_name='actors',
        ),
    ]
