# Generated by Django 3.2.13 on 2023-04-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_user_favorite_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
        ),
    ]
